application: garious
version: 1
runtime: go
api_version: go1

handlers:
- url: /skin
  static_dir: skin

- url: /static
  static_dir: static
  application_readable: true

- url: /yoink
  static_dir: yoink

- url: /.*
  script: _go_app
