application: garious
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /stdlib
  static_dir: yoink/stdlib

- url: /.*
  script: _go_app
